input_data_path: "../dataset/heart_cleveland.csv"
output_model_path: "models/model.pkl"
metric_path: "models/metrics.json"
splitting_params:
  val_size: 0.2
  random_state: 3
train_params:
  model_type: "NaiveBayes"
feature_params:
  categorical_features:
    - "sex"
    - "restecg"
    - "slope"
    - "fbs"
    - "cp"
    - "exang"
    - "thal"
    - "ca"
  numerical_features:
    - "age"
    - "oldpeak"
    - "trestbps"
    - "thalach"
    - "chol"
  target_col: "condition"

